---

- name: "Clean Folder"
  file:
    path: "/home/{{ ansible_user }}/webapp"
    state: absent
- name: Create webapp directory
  file:
    path: "/home/{{ ansible_user }}/webapp/"
    state: directory
#- name: "install selinux-python"
 # yum:
  #  name: libselinux-python3
   # state: present

- name: "git clone to apache folder"
  git:
    repo: https://github.com/diranetafen/static-website-example.git
    dest: /home/{{ ansible_user }}/webapp/

- name: Generate html
  template:
    src: templates/index.html.j2
    dest: "/home/{{ ansible_user }}/webapp/index.html"
- name: "Launching an HTTPD Container"
  docker_container:
    name: apache-server
    image: httpd
    state: started
    ports:
      - "8080:80"
    volumes:
      - "/home/{{ ansible_user }}/webapp:/usr/local/apache2/htdocs/:ro"
